# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design.bd
# Block Designs: The module: 'MIPS_Design' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_File_Register_0_0/MIPS_Design_File_Register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_File_Register_0_0 || ORIG_REF_NAME==MIPS_Design_File_Register_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_IM_0_0/MIPS_Design_IM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_IM_0_0 || ORIG_REF_NAME==MIPS_Design_IM_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_DM_0_0/MIPS_Design_DM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_DM_0_0 || ORIG_REF_NAME==MIPS_Design_DM_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_PC_0_0/MIPS_Design_PC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_PC_0_0 || ORIG_REF_NAME==MIPS_Design_PC_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_Control_Unit_0_0/MIPS_Design_Control_Unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_Control_Unit_0_0 || ORIG_REF_NAME==MIPS_Design_Control_Unit_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_ALU_0_0/MIPS_Design_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_ALU_0_0 || ORIG_REF_NAME==MIPS_Design_ALU_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_2x1_1_0/MIPS_Design_mux_2x1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_2x1_1_0 || ORIG_REF_NAME==MIPS_Design_mux_2x1_1_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_2x1_4_0/MIPS_Design_mux_2x1_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_2x1_4_0 || ORIG_REF_NAME==MIPS_Design_mux_2x1_4_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_Sign_Extention_0_0/MIPS_Design_Sign_Extention_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_Sign_Extention_0_0 || ORIG_REF_NAME==MIPS_Design_Sign_Extention_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_PC_Adder_0_0/MIPS_Design_PC_Adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_PC_Adder_0_0 || ORIG_REF_NAME==MIPS_Design_PC_Adder_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_ALU_Control_0_0/MIPS_Design_ALU_Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_ALU_Control_0_0 || ORIG_REF_NAME==MIPS_Design_ALU_Control_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_util_vector_logic_0_0/MIPS_Design_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_util_vector_logic_0_0 || ORIG_REF_NAME==MIPS_Design_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_addr_0_0/MIPS_Design_mux_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_addr_0_0 || ORIG_REF_NAME==MIPS_Design_mux_addr_0_0} -quiet] -quiet

# IP: d:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_2x1_2_1/MIPS_Design_mux_2x1_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_2x1_2_1 || ORIG_REF_NAME==MIPS_Design_mux_2x1_2_1} -quiet] -quiet

# XDC: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPS_Design'. Do not add the DONT_TOUCH constraint.

# Block Designs: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design.bd
# Block Designs: The module: 'MIPS_Design' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_File_Register_0_0/MIPS_Design_File_Register_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_File_Register_0_0 || ORIG_REF_NAME==MIPS_Design_File_Register_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_IM_0_0/MIPS_Design_IM_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_IM_0_0 || ORIG_REF_NAME==MIPS_Design_IM_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_DM_0_0/MIPS_Design_DM_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_DM_0_0 || ORIG_REF_NAME==MIPS_Design_DM_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_PC_0_0/MIPS_Design_PC_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_PC_0_0 || ORIG_REF_NAME==MIPS_Design_PC_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_Control_Unit_0_0/MIPS_Design_Control_Unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_Control_Unit_0_0 || ORIG_REF_NAME==MIPS_Design_Control_Unit_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_ALU_0_0/MIPS_Design_ALU_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_ALU_0_0 || ORIG_REF_NAME==MIPS_Design_ALU_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_2x1_1_0/MIPS_Design_mux_2x1_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_2x1_1_0 || ORIG_REF_NAME==MIPS_Design_mux_2x1_1_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_2x1_4_0/MIPS_Design_mux_2x1_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_2x1_4_0 || ORIG_REF_NAME==MIPS_Design_mux_2x1_4_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_Sign_Extention_0_0/MIPS_Design_Sign_Extention_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_Sign_Extention_0_0 || ORIG_REF_NAME==MIPS_Design_Sign_Extention_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_PC_Adder_0_0/MIPS_Design_PC_Adder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_PC_Adder_0_0 || ORIG_REF_NAME==MIPS_Design_PC_Adder_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_ALU_Control_0_0/MIPS_Design_ALU_Control_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_ALU_Control_0_0 || ORIG_REF_NAME==MIPS_Design_ALU_Control_0_0} -quiet] -quiet

# IP: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_util_vector_logic_0_0/MIPS_Design_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_util_vector_logic_0_0 || ORIG_REF_NAME==MIPS_Design_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_addr_0_0/MIPS_Design_mux_addr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_addr_0_0 || ORIG_REF_NAME==MIPS_Design_mux_addr_0_0} -quiet] -quiet

# IP: d:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/ip/MIPS_Design_mux_2x1_2_1/MIPS_Design_mux_2x1_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_Design_mux_2x1_2_1 || ORIG_REF_NAME==MIPS_Design_mux_2x1_2_1} -quiet] -quiet

# XDC: D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPS_Design'. Do not add the DONT_TOUCH constraint.
