# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7vx415tffg1158-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/general/University/VHDL/MIPS/MIPS.cache/wt [current_project]
set_property parent.project_path D:/general/University/VHDL/MIPS/MIPS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/general/University/VHDL/MIPS/MIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/File_Register.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/IM.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/DM.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/PC.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/Control_Unit.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/ALU.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/mux_2x1.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/Sign_Extend.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/PC_Adder.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/ALU_Control.vhd
  D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/new/mux_PC.vhd
}
add_files D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design.bd
set_property used_in_implementation false [get_files -all D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MIPS_Design -part xc7vx415tffg1158-2 -mode out_of_context

rename_ref -prefix_all MIPS_Design_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MIPS_Design.dcp
create_report "MIPS_Design_synth_1_synth_report_utilization_0" "report_utilization -file MIPS_Design_utilization_synth.rpt -pb MIPS_Design_utilization_synth.pb"

if { [catch {
  file copy -force D:/general/University/VHDL/MIPS/MIPS.runs/MIPS_Design_synth_1/MIPS_Design.dcp D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/general/University/VHDL/MIPS/MIPS.ip_user_files/bd/MIPS_Design]} {
  catch { 
    file copy -force D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_stub.v D:/general/University/VHDL/MIPS/MIPS.ip_user_files/bd/MIPS_Design
  }
}

if {[file isdir D:/general/University/VHDL/MIPS/MIPS.ip_user_files/bd/MIPS_Design]} {
  catch { 
    file copy -force D:/general/University/VHDL/MIPS/MIPS.srcs/sources_1/bd/MIPS_Design/MIPS_Design_stub.vhdl D:/general/University/VHDL/MIPS/MIPS.ip_user_files/bd/MIPS_Design
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
